### ISSUE TITLE
Use opengl for rendering

### ISSUE THREAD

**Issue by UnsignedArduino** [waycrate/wayboard#9]
Use opengl to render the QGrqphicsView.

Relevant links:
https://doc.qt.io/qt-5/graphicsview.html#opengl-rendering
https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QGraphicsView.html

**Comment by UnsignedArduino** [comment]
Also be able to disable with a cli flag like `--no-opengl`.

**Comment by Shinyzenith** [comment]
why would we be interested in disabling it?

**Comment by Shinyzenith** [comment]
also can we set a dark qt theme by default unless kvantum manager sets one pls?

**Comment by UnsignedArduino** [comment]
> why would we be interested in disabling it?

Debugging and for some reason it doesn't work

**Comment by UnsignedArduino** [comment]
> also can we set a dark qt theme by default unless kvantum manager sets one pls?

Sure. ~~once I figure that out~~

**Comment by Shinyzenith** [comment]
Awesome work !!!

**Comment by Shinyzenith** [comment]
Wayshot is now feature complete, I have moved onto waycast

Once we integrate wayshot + waycast and wayboard we'll be one of the only wayland tools that does all of it with vulkan / opengl context


( waycast will use vulkan acceleration, wayboard will be opengl accelerated )
